<a href="https://colab.research.google.com/github/Jovania/Projetos-01/blob/master/Classificador_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Conjunto de dados flor Iris**

O conjunto de dados consiste em 50 amostras de cada uma das três espécies de Iris ( Iris setosa, Iris virginica e Iris versicolor ). Quatro variáveis foram medidas em cada amostra: o comprimento e a largura das sépalas e pétalas, em centímetros. 

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn import datasets

Bem básico - exibindo os valores do dataset (o comprimento e a largura das sépalas e pétalas), os valores para target, os nomes das flores.



In [ ]:
iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

Visualizando somente os nomes das flores

In [ ]:
print(iris.target_names)


['setosa' 'versicolor' 'virginica']


Visualizando os dados

In [ ]:
print(iris.data)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Visualizando os targets

In [ ]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Visualizando os primeiros elementos de cada grupo. São 3 amostras com 50 flores em cada uma. 
Então temos:
*   0 a 49 flor 'setosa' 
*   50 a 99 flor B  'versicolor'
*  100 a 149 flor C 'virginica'


In [ ]:
print(iris.data[0])
print(iris.target[0])

[5.1 3.5 1.4 0.2]
0


In [ ]:
print(iris.data[50])
print(iris.target[50])

[7.  3.2 4.7 1.4]
1


In [ ]:
print(iris.data[100])
print(iris.target[100])

[6.3 3.3 6.  2.5]
2


Separando os dados para treino e teste. Do conjunto de dados para o treino, serão retirados 3 elementos para o teste. Neste caso, somente para exemplificar, serão retirados os elementos de indices [0], [50, [100]. Poderiam ser retirados quaisquer elementos

In [ ]:
#Test Data Selection
test_idx = [0, 50, 100]

In [ ]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

Deletar do conjunto de treino os elementos que serão usados para o teste.

In [ ]:
# train data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

Identificação do classificador "Decision Tree"

In [ ]:
clf = tree.DecisionTreeClassifier()

Indicação para treinar os dados

In [ ]:
clf.fit(train_data, train_target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

Predizer os dados de teste que são as flores referentes aos indices 0, 50 e 100.

In [ ]:
print(clf.predict(test_data))
print(test_data[0],test_target[0])
print(test_data[1],test_target[1])
print(test_data[2],test_target[2])
#


[0 1 2]
[5.1 3.5 1.4 0.2] 0
[7.  3.2 4.7 1.4] 1
[6.3 3.3 6.  2.5] 2


# **Outra forma de tratar os dados**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = dados e y = target


In [ ]:
X = iris.data
y = iris.target

Através do parâmetro  test_size=0.2, definimos que 20% da amostra de dados será utilizada para testes.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Classificador "Decision Tree" será utilizado, mas poderia ser qualquer outro classificador

In [ ]:
my_classifier = tree.DecisionTreeClassifier()

"Fit" é o método para treinar a rede

In [ ]:
my_classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

Predição realizada nos dados de teste

In [ ]:
predictions = my_classifier.predict(X_test)

Dados estatísticos das predições para árvores de Decisão

In [ ]:
print(accuracy_score(y_test, predictions))

0.9333333333333333


# **Apenas alterando o Classificador para o KNN**

O princípio por trás dos métodos de vizinho mais próximo é encontrar um número predefinido de amostras de treinamento mais próximas em distância do novo ponto e prever o rótulo a partir deles. O número de amostras pode ser uma constante definida pelo usuário (aprendizado de k-vizinho mais próximo) ou variar com base na densidade local de pontos (aprendizado de vizinho baseado em raio). A distância pode, em geral, ser qualquer medida métrica: a distância euclidiana padrão é a escolha mais comum. Os métodos baseados em vizinhos são conhecidos como métodos de aprendizado de máquina não generalizantes , pois eles simplesmente “lembram” todos os seus dados de treinamento (possivelmente transformados em uma estrutura de indexação rápida, como uma Ball Tree ou KD Tree ).

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [56]:
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
my_classifier = KNeighborsClassifier()
my_classifier.fit(X_train, y_train)
predictions = my_classifier.predict(X_test)
print(accuracy_score(y_test, predictions))

0.9777777777777777


Alterando para que os dados de teste sejam maiores que os dados de treino, então teremos uma acurácia menor, pois menos dados serão treinados (aprendidos) pela rede.